.TH "Arrow" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arrow \- Structure representing an arrow in the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Arrow\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdirection\fP"
.br
.ti -1c
.RI "\fBRect\fP \fBarrowPos\fP"
.br
.ti -1c
.RI "double \fBangleRotate\fP"
.br
.ti -1c
.RI "int \fBspeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing an arrow in the game\&. 

This structure holds information about the direction, position, rotation angle, and speed of an arrow projectile in the game\&. 
.SH "Member Data Documentation"
.PP 
.SS "double Arrow::angleRotate"
Rotation angle of the arrow\&. 
.SS "\fBRect\fP Arrow::arrowPos"
\fBPosition\fP and size of the arrow\&. 
.SS "int Arrow::direction"
Direction of the arrow\&. 
.SS "int Arrow::speed"
Speed of the arrow\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
