.TH "D:/CLion-Project/MY_Project/myGame/src/core/config.h" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/CLion-Project/MY_Project/myGame/src/core/config.h \- Project constants\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'SDL\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWINDOW_TITLE\fP   'Hunter Assassin'"
.br
.ti -1c
.RI "#define \fBWINDOW_X\fP   SDL_WINDOWPOS_UNDEFINED"
.br
.ti -1c
.RI "#define \fBWINDOW_Y\fP   SDL_WINDOWPOS_UNDEFINED"
.br
.ti -1c
.RI "#define \fBWINDOW_W\fP   900"
.br
.ti -1c
.RI "#define \fBWINDOW_H\fP   600"
.br
.ti -1c
.RI "#define \fBPLAYER_WIDTH\fP   64"
.br
.ti -1c
.RI "#define \fBPLAYER_HEIGHT\fP   64"
.br
.ti -1c
.RI "#define \fBWIDTH_A\fP   64"
.br
.ti -1c
.RI "#define \fBHEIGHT_A\fP   64"
.br
.ti -1c
.RI "#define \fBLEN\fP   44"
.br
.ti -1c
.RI "#define \fBARR_SPEED\fP   6"
.br
.in -1c
.SH "Detailed Description"
.PP 
Project constants\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define HEIGHT_A   64"
Height of the sprite\&. 
.SS "#define LEN   44"
Size of buffer\&. 
.SS "#define PLAYER_HEIGHT   64"
Height of the player\&. 
.SS "#define PLAYER_WIDTH   64"
Width of the player\&. 
.SS "#define WIDTH_A   64"
Width of the sprite\&. 
.SS "#define WINDOW_H   600"
Height of the window\&. 
.SS "#define WINDOW_TITLE   'Hunter Assassin'"
Title of the game window\&. 
.SS "#define WINDOW_W   900"
Width of the window\&. 
.SS "#define WINDOW_X   SDL_WINDOWPOS_UNDEFINED"
Horizontal position of the window\&. 
.SS "#define WINDOW_Y   SDL_WINDOWPOS_UNDEFINED"
Vertical position of the window\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
