.TH "D:/CLion-Project/MY_Project/myGame/src/core/Direction.h" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/CLion-Project/MY_Project/myGame/src/core/Direction.h \- Defines directional constants for movement\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNORTH\fP = 0, \fBWEST\fP = 1, \fBEAST\fP = 3, \fBSOUTH\fP = 2 }"
.br
.RI "Enumeration of directional constants\&. NORTH represents upward movement\&. WEST represents leftward movement\&. EAST represents rightward movement\&. SOUTH represents downward movement\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines directional constants for movement\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
Enumeration of directional constants\&. NORTH represents upward movement\&. WEST represents leftward movement\&. EAST represents rightward movement\&. SOUTH represents downward movement\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINORTH \fP\fP
Upward direction constant\&. 
.TP
\fB\fIWEST \fP\fP
Leftward direction constant\&. 
.TP
\fB\fIEAST \fP\fP
Rightward direction constant\&. 
.TP
\fB\fISOUTH \fP\fP
Downward direction constant\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
