.TH "Position" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- Structure representing a position in a 2D space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <point\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "x-coordinate of the position\&. "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "y-coordinate of the position\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a position in a 2D space\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
