.TH "Rect" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rect \- Structure representing a rectangle in a 2D space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "x-coordinate of the top-left corner of the rectangle\&. "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "y-coordinate of the top-left corner of the rectangle\&. "
.ti -1c
.RI "int \fBw\fP"
.br
.RI "Width of the rectangle\&. "
.ti -1c
.RI "int \fBh\fP"
.br
.RI "Height of the rectangle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a rectangle in a 2D space\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
