.TH "SDLGame" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLGame \- Class managing the game with SDL display\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SDLGame\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDLGame\fP ()"
.br
.RI "Default constructor of the \fBSDLGame\fP class\&. "
.ti -1c
.RI "\fB~SDLGame\fP ()"
.br
.RI "Destructor of the \fBSDLGame\fP class\&. "
.ti -1c
.RI "void \fBrunProject\fP ()"
.br
.RI "Main method to run the game\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class managing the game with SDL display\&. 

This class handles the main game loop and SDL display, including initializing the game, running the game loop, and cleaning up resources\&. 
.SH "Member Function Documentation"
.PP 
.SS "void SDLGame::runProject ()"

.PP
Main method to run the game\&. This method initializes the SDL window and renderer, starts the game loop, handles user input, updates game state, and renders graphics until the game ends\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
