.TH "D:/CLion-Project/MY_Project/myGame/src/sdl2/SDLSprite.h" 3 "Hunter-Assassin PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/CLion-Project/MY_Project/myGame/src/sdl2/SDLSprite.h \- Definition of the \fBSDLSprite\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'SDL\&.h'\fP
.br
\fR#include '\&.\&./core/Rect\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSDLSprite\fP"
.br
.RI "Class for handling SDL sprites\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBSDLSprite\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Hunter-Assassin PROJECT from the source code\&.
