
#ifndef HUNTERASSASSIN_CONFIG_VARIABLE_H
#define HUNTERASSASSIN_CONFIG_VARIABLE_H
/*
///Les constantes du projet
#define WINDOW_TITLE "Hunter Assassin"
#define WINDOW_X SDL_WINDOWPOS_UNDEFINED
#define WINDOW_Y SDL_WINDOWPOS_UNDEFINED

//#define WINDOW_W 299 //550 chez gold
//#define WINDOW_H 550 //850 chez gold
#define PLAYER_WIDTH 24
#define PLAYER_HEIGHT 36*/

#endif //HUNTERASSASSIN_CONFIG_VARIABLE_H
